[build]
  command = "pip install -r requirements.txt"
  publish = "src/web"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["python-shell"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 